### ISSUE TITLE
context of the data

### ISSUE THREAD

**Issue by chijames** [asappresearch/dialog-intent-induction#10]
Hi,

Thanks for sharing the code! One question, is it possible to separate the context into different utterances? Since currently the context is constructed by merging user and system utterances if I understand correctly.

Thanks.

**Comment by hpasapp** [comment]
Which dataset do you mean? For askubuntu, the dataset preparation is something like:

```
export PYTHONPATH=.
mkdir ~/data/askubuntu_induction
python datasets/askubuntu_preprocess.py create-labeled --out-labeled ~/data/askubuntu_induction/preproc_labeled.csv
python datasets/askubuntu_preprocess.py create-unlabeled --out-unlabeled ~/data/askubuntu_induction/preproc_unlabeled.csv
python datasets/labeled_unlabeled_merger.py --labeled-files ~/data/askubuntu_induction/preproc_labeled.csv --unlabeled-files ~/data/askubuntu_induction/preproc_unlabeled.csv --out-file ~/data/askubuntu_induction/preproc_merged.csv --labeled-columns view1=question_title,label=cluster_id --unlabeled-columns view1=question_title,view2=answer_body --no-add-cust-tokens
```
It looks like that last script isn't included in this repo, but we can probably add that if needed.

Given the scripts to create the dataset, you would then be able to modify the script to produce the output in the format you prefer.

**Comment by chijames** [comment]
Thanks for the reply! It will be nice if the last script you mentioned can be included :)

For the original question, I was referring to the twitter airline dataset. I tried to separate the context using ".", but the result does not seem correct. Is it possible to also share the preprocessing script of twitter dataset?

Thanks!

**Comment by hpasapp** [comment]
Ok, so the commands will be something like:

```
(cd data; bunzip2 airlines_500onlyb.csv.bz2)
python datasets/twitter_dataset_preprocess.py --no-preprocess --out-examples ~/data/twittersupport/airlines_raw.csv
python datasets/twitter_airlines_raw_merger2.py
```
I need to look into adding these scripts into this repo. This might take several days. Please remind me every 3-4 days until I do this.

**Comment by hpasapp** [comment]
Hi, can you check this branch, https://github.com/asappresearch/dialog-intent-induction/compare/add-dataset-scripts?expand=1 and let me know to what extent that works ok for you?

**Comment by chijames** [comment]
Sorry for the late reply. Yes! This works like a charm. I just need to add "run-aggregated" to the command. Thanks for your timely help.

**Comment by hpasapp** [comment]
Awesome! :)
